### PR TITLE
Use > 256 code points

### PR DESCRIPTION
**Pull request by vinbo8**
I know this is `master` but I _think_ it should behave the same as it does now for Latin.

### CODE REVIEW

**Comment by akutuzov** [comment]
Thanks!
Let me first test it on real data, and then I will merge.

**Comment by akutuzov** [comment]
Nope, it throws errors at training time and fails:

```
in _build_word_char_embeddings
  (1) Invalid argument: indices[21,1,1] = 23439 is not in [0, 261)
         [[{{node lm/embedding_lookup}}]]
         [[lm_1/gradients/lm_1/sampled_softmax_loss_1/embedding_lookup_grad/Cast/_337]]
```
Trying to find the number of characters, which would incorporate all we need, but still not be the total number of unicode code points (more than a million).

**Comment by akutuzov** [comment]
OK, after increasing the `n_characters` parameter in `train_elmo.py` to 256000 (from 261), it is training without errors. But the process is, like, 3 times slower than usual.
After it finishes, I will compare the performance of this model with the one trained in the regular way.

**Comment by vinbo8** [comment]
Maybe it's a good idea to just build a character vocabulary..

— v.

**Comment by akutuzov** [comment]
OK, I tested a model trained this way. It trains much longer than usual and ends up to be marginally heavier in size (not surprisingly). 
But most important is that the resulting ELMo performs consistently worse at least on the WSD task (I tested on two different languages). Thus, I don't think it makes sense to mess with the original code in this way.
Instead, I've committed a [simple script](https://github.com/ltgoslo/simple_elmo_training/blob/master/count_long_words.py) which analyzes a prospective training corpus by calculating the average number of bytes per character. It will also predict the number of word types and word tokens which will be cropped at training time.

**Pull request closed without merging**
